#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format code
find ./src -iname *.h -o -iname *.cpp | xargs clang-format -i

# Prevent to commit on master and develop
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to master branch"
  exit 1
fi

if [ "$branch" = "develop" ]; then
  echo "You can't commit directly to develop branch"
  exit 1
fi